<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutDir>..\1.6\Assemblies\</OutDir>
	</PropertyGroup>

	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>TRACE;NDEBUG;V1_6</DefineConstants>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>TRACE;DEBUG;V1_6</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
		<PackageReference Include="Lib.Harmony" Version="2.3.6" ExcludeAssets="runtime" />
		<PackageReference Update="Krafs.Publicizer" Version="2.3.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
